name = "TreatmentPanels"
uuid = "7885c543-3ac4-48a3-abed-7a36d7ddb69f"
authors = ["Nils <nils@gudat.uk> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1"
DataFrames = "1"
RecipesBase = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
